// Code generated by options-gen v0.55.5. DO NOT EDIT.

package options

type OptHandlerOptionsSetter func(o *HandlerOptions)

func NewHandlerOptions(
	options ...OptHandlerOptionsSetter,
) HandlerOptions {
	var o HandlerOptions

	// Setting defaults from field tag (if present)

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func WithAuthSecret(opt string) OptHandlerOptionsSetter {
	return func(o *HandlerOptions) { o.AuthSecret = opt }
}

func WithPinger(opt interface{}) OptHandlerOptionsSetter {
	return func(o *HandlerOptions) { o.Pinger = opt }
}

func WithAuditor(opt interface{}) OptHandlerOptionsSetter {
	return func(o *HandlerOptions) { o.Auditor = opt }
}

// TrustedSubnet — строковый CIDR доверенной подсети для эндпоинта /api/internal/stats.
// Пустое значение запрещает доступ к эндпоинту для любых запросов.
func WithTrustedSubnet(opt string) OptHandlerOptionsSetter {
	return func(o *HandlerOptions) { o.TrustedSubnet = opt }
}

func (o *HandlerOptions) Validate() error {
	return nil
}
