// cmd/reset генерирует методы Reset() для структур с комментарием // generate:reset.
// Запускать из корня проекта: go run ./cmd/reset/
package main

import (
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"unicode"
)

var primitives = map[string]string{
	"int":        "0",
	"int8":       "0",
	"int16":      "0",
	"int32":      "0",
	"int64":      "0",
	"uint":       "0",
	"uint8":      "0",
	"uint16":     "0",
	"uint32":     "0",
	"uint64":     "0",
	"uintptr":    "0",
	"float32":    "0",
	"float64":    "0",
	"complex64":  "0",
	"complex128": "0",
	"string":     `""`,
	"bool":       "false",
	"byte":       "0",
	"rune":       "0",
}

type structInfo struct {
	name   string
	fields []*ast.Field
}

type pkgInfo struct {
	name    string
	structs []structInfo
}

func main() {
	root := "."
	if len(os.Args) > 1 {
		root = os.Args[1]
	}

	packages, err := walkPackages(root)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error walking packages: %v\n", err)
		os.Exit(1)
	}

	generated := 0
	for dir, pkg := range packages {
		if len(pkg.structs) == 0 {
			continue
		}
		if err := generateFile(dir, pkg); err != nil {
			fmt.Fprintf(os.Stderr, "error generating %s/reset.gen.go: %v\n", dir, err)
			os.Exit(1)
		}
		fmt.Printf("generated %s/reset.gen.go (%d structs)\n", dir, len(pkg.structs))
		generated++
	}
	if generated == 0 {
		fmt.Println("no // generate:reset structs found")
	}
}

func walkPackages(root string) (map[string]*pkgInfo, error) {
	packages := make(map[string]*pkgInfo)

	err := filepath.WalkDir(root, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			name := d.Name()
			if path != "." && (name == "vendor" || strings.HasPrefix(name, ".")) {
				return filepath.SkipDir
			}
			return nil
		}
		if !strings.HasSuffix(path, ".go") ||
			strings.HasSuffix(path, "_test.go") ||
			strings.HasSuffix(path, ".gen.go") {
			return nil
		}

		dir := filepath.Dir(path)
		structs, pkgName, err := parseFile(path)
		if err != nil || len(structs) == 0 {
			return err
		}

		if _, ok := packages[dir]; !ok {
			packages[dir] = &pkgInfo{name: pkgName}
		}
		packages[dir].structs = append(packages[dir].structs, structs...)
		return nil
	})

	return packages, err
}

func parseFile(path string) ([]structInfo, string, error) {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
	if err != nil {
		return nil, "", err
	}

	var structs []structInfo
	for _, decl := range f.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.TYPE {
			continue
		}
		if !hasGenerateReset(genDecl.Doc) {
			continue
		}
		for _, spec := range genDecl.Specs {
			ts, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}
			st, ok := ts.Type.(*ast.StructType)
			if !ok {
				continue
			}
			structs = append(structs, structInfo{
				name:   ts.Name.Name,
				fields: st.Fields.List,
			})
		}
	}

	return structs, f.Name.Name, nil
}

func hasGenerateReset(doc *ast.CommentGroup) bool {
	if doc == nil {
		return false
	}
	for _, c := range doc.List {
		if strings.TrimSpace(c.Text) == "// generate:reset" {
			return true
		}
	}
	return false
}

func generateFile(dir string, pkg *pkgInfo) error {
	var b strings.Builder
	b.WriteString("// Code generated by cmd/reset; DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n", pkg.name)

	for _, s := range pkg.structs {
		b.WriteString(generateResetMethod(s))
	}

	src, err := format.Source([]byte(b.String()))
	if err != nil {
		return fmt.Errorf("format error: %w\n--- source ---\n%s", err, b.String())
	}

	return os.WriteFile(filepath.Join(dir, "reset.gen.go"), src, 0644)
}

func generateResetMethod(s structInfo) string {
	recv := receiverName(s.name)
	var b strings.Builder

	fmt.Fprintf(&b, "\nfunc (%s *%s) Reset() {\n", recv, s.name)
	fmt.Fprintf(&b, "\tif %s == nil {\n\t\treturn\n\t}\n", recv)

	for _, field := range s.fields {
		for _, name := range field.Names {
			line := fieldResetLine(recv, name.Name, field.Type)
			if line != "" {
				b.WriteString("\t" + line + "\n")
			}
		}
		// анонимные (встроенные) поля
		if len(field.Names) == 0 {
			anonName := anonFieldName(field.Type)
			if anonName != "" {
				line := fieldResetLine(recv, anonName, field.Type)
				if line != "" {
					b.WriteString("\t" + line + "\n")
				}
			}
		}
	}

	b.WriteString("}\n")
	return b.String()
}

func fieldResetLine(recv, name string, typ ast.Expr) string {
	switch t := typ.(type) {
	case *ast.Ident:
		if zero, ok := primitives[t.Name]; ok {
			return fmt.Sprintf("%s.%s = %s", recv, name, zero)
		}
		// именованный тип — проверяем через интерфейс
		return resetterCheckLine(recv, name, "")

	case *ast.StarExpr:
		return pointerResetLine(recv, name, t.X)

	case *ast.ArrayType:
		if t.Len == nil {
			// слайс
			return fmt.Sprintf("%s.%s = %s.%s[:0]", recv, name, recv, name)
		}
		// массив фиксированной длины — пропускаем
		return ""

	case *ast.MapType:
		return fmt.Sprintf("clear(%s.%s)", recv, name)

	case *ast.SelectorExpr:
		// внешний тип pkg.Type — проверяем через интерфейс
		return resetterCheckLine(recv, name, "")

	case *ast.InterfaceType, *ast.FuncType, *ast.ChanType:
		return ""
	}
	return ""
}

func pointerResetLine(recv, name string, inner ast.Expr) string {
	switch t := inner.(type) {
	case *ast.Ident:
		if zero, ok := primitives[t.Name]; ok {
			return fmt.Sprintf("if %s.%s != nil {\n\t\t*%s.%s = %s\n\t}", recv, name, recv, name, zero)
		}
		// указатель на именованный тип
		return resetterCheckLine(recv, name, fmt.Sprintf(" && %s.%s != nil", recv, name))
	case *ast.SelectorExpr:
		return resetterCheckLine(recv, name, fmt.Sprintf(" && %s.%s != nil", recv, name))
	case *ast.ArrayType:
		if t.Len == nil {
			return fmt.Sprintf("if %s.%s != nil {\n\t\t*%s.%s = (*%s.%s)[:0]\n\t}", recv, name, recv, name, recv, name)
		}
		return ""
	case *ast.MapType:
		return fmt.Sprintf("if %s.%s != nil {\n\t\tclear(*%s.%s)\n\t}", recv, name, recv, name)
	}
	return ""
}

// resetterCheckLine строит блок, вызывающий Reset() у поля recv.name,
// если оно реализует интерфейс { Reset() }. extraCond — дополнительное
// условие (например, проверка на nil для указателей), добавляемое в if
// после основной проверки типа.
func resetterCheckLine(recv, name, extraCond string) string {
	return fmt.Sprintf(
		"if resetter, ok := any(%s.%s).(interface{ Reset() }); ok%s {\n\t\tresetter.Reset()\n\t}",
		recv, name, extraCond,
	)
}

// receiverName строит короткое имя ресивера из CamelCase имени структуры.
func receiverName(name string) string {
	var b strings.Builder
	for _, r := range name {
		if unicode.IsUpper(r) {
			b.WriteRune(unicode.ToLower(r))
		}
	}
	if b.Len() == 0 {
		return strings.ToLower(name[:1])
	}
	return b.String()
}

func anonFieldName(typ ast.Expr) string {
	switch t := typ.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.SelectorExpr:
		return t.Sel.Name
	case *ast.StarExpr:
		return anonFieldName(t.X)
	}
	return ""
}
